version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - postgres.env
    networks:
      app_network:
        aliases:
          - postgresdb

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - postgres.env
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge